# CO2 VEHICAL DATESET
## Step 1: Download Datset

# Step 2: Preprocessing

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving co2.csv to co2.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Load uploaded Kaggle dataset
df = pd.read_csv("/content/co2.csv")   # Make sure name matches uploaded file
print("Original dataset shape:", df.shape)

Original dataset shape: (7385, 12)

In [ ]:
print(df.head())

    Make       Model Vehicle Class  Engine Size(L)  Cylinders Transmission  \
0  ACURA         ILX       COMPACT             2.0          4          AS5
1  ACURA         ILX       COMPACT             2.4          4           M6
2  ACURA  ILX HYBRID       COMPACT             1.5          4          AV7
3  ACURA     MDX 4WD   SUV - SMALL             3.5          6          AS6
4  ACURA     RDX AWD   SUV - SMALL             3.5          6          AS6

  Fuel Type  Fuel Consumption City (L/100 km)  \
0         Z                               9.9
1         Z                              11.2
2         Z                               6.0
3         Z                              12.7
4         Z                              12.1

   Fuel Consumption Hwy (L/100 km)  Fuel Consumption Comb (L/100 km)  \
0                              6.7                               8.5
1                              7.7                               9.6
2                              5.8                               5.9
3                              9.1                              11.1
4                              8.7                              10.6

   Fuel Consumption Comb (mpg)  CO2 Emissions(g/km)
0                           33                  196
1                           29                  221
2                           48                  136
3                           25                  255
4                           27                  244

In [ ]:
df.isnull()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,False,False,False,False,False,False,False,False,False,False,False,False
7381,False,False,False,False,False,False,False,False,False,False,False,False
7382,False,False,False,False,False,False,False,False,False,False,False,False
7383,False,False,False,False,False,False,False,False,False,False,False,False
7384,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Convert fuel consumption (L/100km) -> Mileage (km per litre)
df["mileage_kmpl"] = 100 / df["Fuel Consumption Comb (L/100 km)"]
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),mileage_kmpl
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,11.764706
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,10.416667
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,16.949153
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,9.009009
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,9.433962
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,10.638298
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240,9.708738
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248,9.345794

In [ ]:
# Standardize fuel type
df["fuel_type"] = df["Fuel Type"].replace({
    "Z": "Petrol",
    "X": "Petrol",
    "D": "Diesel",
    "E": "Ethanol",
    "N": "Natural Gas"
})
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),mileage_kmpl,fuel_type
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,11.764706,Petrol
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,10.416667,Petrol
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,16.949153,Petrol
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,9.009009,Petrol
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,9.433962,Petrol
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,10.638298,Petrol
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240,9.708738,Petrol
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248,9.345794,Petrol

In [ ]:
# Assign emission factors (kg CO₂ per litre of fuel)
emission_factors = {"Petrol": 2.31, "Diesel": 2.68, "Natural Gas": 2.74, "Ethanol": 1.91, "EV": 0}
df["emission_factor"] = df["fuel_type"].map(emission_factors)

In [ ]:
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),mileage_kmpl,fuel_type,emission_factor
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,11.764706,Petrol,2.31
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,10.416667,Petrol,2.31
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,16.949153,Petrol,2.31
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,9.009009,Petrol,2.31
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,9.433962,Petrol,2.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,10.638298,Petrol,2.31
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240,9.708738,Petrol,2.31
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248,9.345794,Petrol,2.31

In [ ]:
# Vehicle type (car vs truck) based on Vehicle Class
df["vehicle_type"] = df["Vehicle Class"].apply(
    lambda x: "Truck" if "TRUCK" in x.upper() else "Car"
)


# Synthetic features

In [ ]:
# Synthetic features
n = len(df)
df["load_weight"] = np.where(df["vehicle_type"]=="Truck",
                             np.random.randint(5000,20000,n), np.random.randint(50,2000,n))
df["vehicle_age"] = np.where(df["vehicle_type"]=="Truck",
                             np.random.randint(0,20,n),
                             np.random.randint(0,15,n))
df["maintenance_efficiency"] = np.round(np.random.uniform(0.7,1.0,n), 2)

In [ ]:
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),mileage_kmpl,fuel_type,emission_factor,vehicle_type,load_weight,vehicle_age,maintenance_efficiency
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,11.764706,Petrol,2.31,Car,1353,14,0.83
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,10.416667,Petrol,2.31,Car,1287,8,0.99
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,16.949153,Petrol,2.31,Car,1660,0,0.77
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,9.009009,Petrol,2.31,Car,1824,4,0.80
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,9.433962,Petrol,2.31,Car,894,12,0.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,10.638298,Petrol,2.31,Car,1416,2,0.84
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31,Car,469,7,0.86
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240,9.708738,Petrol,2.31,Car,1756,9,0.74
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31,Car,270,12,0.86
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248,9.345794,Petrol,2.31,Car,1991,4,0.82

In [ ]:
final_df = df[[
    "vehicle_type","fuel_type","mileage_kmpl","load_weight",
    "emission_factor","vehicle_age","maintenance_efficiency",
    "CO2 Emissions(g/km)"
]].rename(columns={"CO2 Emissions(g/km)": "co2_emission"})
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),mileage_kmpl,fuel_type,emission_factor,vehicle_type,load_weight,vehicle_age,maintenance_efficiency
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196,11.764706,Petrol,2.31,Car,1353,14,0.83
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221,10.416667,Petrol,2.31,Car,1287,8,0.99
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136,16.949153,Petrol,2.31,Car,1660,0,0.77
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255,9.009009,Petrol,2.31,Car,1824,4,0.80
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244,9.433962,Petrol,2.31,Car,894,12,0.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219,10.638298,Petrol,2.31,Car,1416,2,0.84
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31,Car,469,7,0.86
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240,9.708738,Petrol,2.31,Car,1756,9,0.74
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232,10.101010,Petrol,2.31,Car,270,12,0.86
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248,9.345794,Petrol,2.31,Car,1991,4,0.82

In [ ]:
print("Final Dataset Shape:", final_df.shape)
print(final_df.head())

Final Dataset Shape: (7385, 8)
  vehicle_type fuel_type  mileage_kmpl  load_weight  emission_factor  \
0          Car    Petrol     11.764706         1353             2.31
1          Car    Petrol     10.416667         1287             2.31
2          Car    Petrol     16.949153         1660             2.31
3          Car    Petrol      9.009009         1824             2.31
4          Car    Petrol      9.433962          894             2.31

   vehicle_age  maintenance_efficiency  co2_emission
0           14                    0.83           196
1            8                    0.99           221
2            0                    0.77           136
3            4                    0.80           255
4           12                    0.88           244

In [ ]:
final_df.to_csv("EcoSphereAI_Final.csv", index=False)
print("✅ Saved processed dataset as EcoSphereAI_Final.csv")

✅ Saved processed dataset as EcoSphereAI_Final.csv

# Step 3: Model making

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X = final_df.drop(columns=["co2_emission"])
y = final_df["co2_emission"]

categorical_features = ["vehicle_type", "fuel_type"]
numeric_features = ["mileage_kmpl","load_weight","emission_factor","vehicle_age","maintenance_efficiency"]

# Preprocessor
preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("num", "passthrough", numeric_features)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:

from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [ ]:
# Random Forest
rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", RandomForestRegressor(n_estimators=100, random_state=42))
])
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

print("\n🔹 Random Forest Results")
print("R²:", r2_score(y_test, rf_preds))
print("MAE:", mean_absolute_error(y_test, rf_preds))
print("RMSE:", np.sqrt(mean_squared_error(y_test, rf_preds)))

🔹 Random Forest Results
R²: 0.9961624299042015
MAE: 2.420873392010833
RMSE: 3.6331544567638163

In [ ]:
# XGBoost
xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(n_estimators=100, max_depth=5, learning_rate=0.1,
                               random_state=42, objective="reg:squarederror"))
])
xgb_model.fit(X_train, y_train)
xgb_preds = xgb_model.predict(X_test)

print("\n🔹 XGBoost Results")
print("R²:", r2_score(y_test, xgb_preds))
print("MAE:", mean_absolute_error(y_test, xgb_preds))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_preds)))

🔹 XGBoost Results
R²: 0.9960500597953796
MAE: 2.287950277328491
RMSE: 3.685962162363842

In [ ]:
# Save Best Model
import joblib
joblib.dump(rf_model, "EcoSphereAI_RFModel.pkl")
print("✅ Random Forest Model Saved as EcoSphereAI_RFModel.pkl")

✅ Random Forest Model Saved as EcoSphereAI_RFModel.pkl

In [ ]:

# Load saved model
model = joblib.load("EcoSphereAI_RFModel.pkl")

# Step 4: Output Prediction

In [ ]:
#Predict from User Input
import joblib
import pandas as pd

# Load trained model
model = joblib.load("EcoSphereAI_RFModel.pkl")

print("🚗 Enter vehicle details to predict CO₂ emission")

vehicle_type = input("Enter Vehicle Type (Car/Truck): ")
fuel_type = input("Enter Fuel Type (Petrol/Diesel/CNG/Ethanol/EV): ")
mileage_kmpl = float(input("Enter Mileage (km/l): "))
load_weight = float(input("Enter Load Weight (kg): "))
emission_factor = float(input("Enter Emission Factor (Petrol=2.31, Diesel=2.68, CNG=2.74, Ethanol=1.91, EV=0): "))
vehicle_age = int(input("Enter Vehicle Age (years): "))
maintenance_efficiency = float(input("Enter Maintenance Efficiency (0.7 to 1.0): "))

# Build input DataFrame
user_input = pd.DataFrame([{
    "vehicle_type": vehicle_type,
    "fuel_type": fuel_type,
    "mileage_kmpl": mileage_kmpl,
    "load_weight": load_weight,
    "emission_factor": emission_factor,
    "vehicle_age": vehicle_age,
    "maintenance_efficiency": maintenance_efficiency
}])

# Predict CO₂ emission
prediction = model.predict(user_input)[0]

print("\n✅ Predicted CO₂ Emission:", round(prediction, 2), "g/km")

🚗 Enter vehicle details to predict CO₂ emission
Enter Vehicle Type (Car/Truck): Car
Enter Fuel Type (Petrol/Diesel/CNG/Ethanol/EV): EV
Enter Mileage (km/l): 15
Enter Load Weight (kg): 100
Enter Emission Factor (Petrol=2.31, Diesel=2.68, CNG=2.74, Ethanol=1.91, EV=0): 0
Enter Vehicle Age (years): 5
Enter Maintenance Efficiency (0.7 to 1.0): 0.9

✅ Predicted CO₂ Emission: 165.24 g/km